### ISSUE TITLE
Trackr automatically compile information from different trials

### ISSUE THREAD

**Issue by larroca** [Ax3man/trackr#25]
The package is automatically combining data from different trials into one trial. I have realized that the way that I have named the files is causing this problem. For instance, I have several individuals from the same treatment which I have named XXXX1.1.csv; XXXX1.2.csv; XXXX1.3.csv, and the tracks from these individuals are then combined in the data as only one track. I have renamed the files using a numerical sequence and this problem disappear.

I attach an example with 9 files that get combined into only 6 tracks using the following code:

files<-list.files(startingDir, pattern="csv")
dat <- read_Ctrax(files, type = 'fixed')
tr <- as_tracks(dat, frame_rate = 30)
plot(tr)

[tracktest.zip](https://github.com/Ax3man/trackr/files/804599/tracktest.zip)

Thanks!

**Comment by Ax3man** [comment]
OK, I see. It's the period (`.`) that is causing the problem. My naive code is only keeping the name before the period. This is easy to fix and will be fixed very soon.

Thanks for the clear report!

**Comment by larroca** [comment]
Many thanks for the work!

I have reinstalled now the package and tried again with the nine files provided. I'm afraid that this time they get combined all as one trial named character(0).

I also get the following warning:

Warning message:
In `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  :
  duplicated levels in factors are deprecated

**Comment by Ax3man** [comment]
Sorry about that. Hopefully it is fixed properly now.

**Comment by larroca** [comment]
It's working fine for me now. Thanks for the work!
