### ISSUE TITLE
Turn

### ISSUE THREAD

**Issue by Ariannaleira** [Ax3man/trackr#31]
Hi,
I downloaded your package and as I was going through it using your example data I came across this error:

Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'turn' of mode 'function' was not found

I have installed all the mentioned packages with the library function, and followed every single step you posted, also tried doing it all with my data but it still shows the same error, could you help me? 

Thank you!
Ari

**Comment by Ax3man** [comment]
Sorry, I believe I renamed that function to `angular_velocity`.
